# Site settings
title: CodeHu
url: "mickeyliu5.github.io"    # the protocol and hostname of your site, eg. `http://zhaoyuxiang.cn/blog`
baseurl: "" # the prefix of your site uri, eg. `/bohu-jekyll-theme` or just one slash `/`
#timezone: Asia/Shanghai
description: Coding is fun
# Your information
email: jason.yyliu@gmail.com
author: Jason Liu
place: New York
domain: mickeyliu5.github.io
company: Unknown
position: Engineer
school: USTC
major: Science
resume: ""
profile: Time is money. 
twitter_username: 
weibo_username: u/2631341093
github_username:  mickeyliu5
linkedin_username: in/yuanresume

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: zhaoyuxiang   
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: clark-zhao  
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 30
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
