# Site settings
title: CodeHu
url: "http://www.jasonjson.com"    # the protocol and hostname of your site, eg. `http://zhaoyuxiang.cn/blog`
baseurl: "" # the prefix of your site uri, eg. `/bohu-jekyll-theme` or just one slash `/`
#timezone: Asia/Shanghai
description: Coding is fun
# Your information
email: jason.yyliu@gmail.com
author: Jason Liu
place: New York
domain: www.jasonjson.com
company: Unknown
position: Engineer
school: USTC
major: Geophysics
#resume:
profile: Time is money.
#twitter_username:
github_username: jasonjson
linkedin_username: in/yuanresume
google_analytics: UA-90046803-1

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: mickeyliu5
# get one: https://disqus.com/admin/signup/
#duoshuo_shortname: mickeyliu5
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-feed

# Build settings
paginate: 30
paginate_path: "/blog/page:num/"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
